### ISSUE TITLE
View.Tag == null

### ISSUE THREAD

**Issue by samosim** [sumeyyaarar/XamarinFormsCustomPicker#1]
Hi Sümeyya Tuğçe Arar

First of all thanks for this amazing project. I tested your code and it works properly. After that, I transferred your code into my project in which I have had an issue. The method OnClick in CustomPickerListener is properly triggered but variable var renderer = v.Tag as CustomPickerRenderer is null. Do you may know what can be the reason for this behavior.  If I implement Control.Click += Control_Click event handler everything works fine. However, I think that your approach is a more elegant solution. 

I will appreciate any feedback. 

Best regards
Samo

**Comment by rcarretteGroupeBRIAND** [comment]
Hi, thanks for the hard work but same problem here.

I downloaded your sample app and I keep getting `v.Tag as CustomPickerRenderer` as null. As said above, implementing the Click handler fixes it, but it's not very clean.

**Comment by samosim** [comment]
It seems that we will not get a reply...

**Comment by sumeyyaarar** [comment]
Hello, thanks for your feedback and sorry for late reply. I am looking into it.
