### ISSUE TITLE
Null Oldelemnt

### ISSUE THREAD

**Issue by BalsamIbrahim** [sumeyyaarar/XamarinFormsCustomPicker#2]
I used the code but when I run the program it throw an exception
![2019-11-17_1606](https://user-images.githubusercontent.com/34779906/69008544-2fad2280-0954-11ea-9d93-64e1077d3615.png)

**Comment by sumeyyaarar** [comment]
Hello Balsam, 

Thank you, I look into it.

**Comment by sumeyyaarar** [comment]
Hello again, can you please move the code line

**Comment by sumeyyaarar** [comment]
Hello again, can you please move the code line
`base.OnElementChanged(e);`
start of the method. It should be look like this:
` base.OnElementChanged(e);
            if (e.NewElement == null) return;
            customPicker = e.NewElement as CustomPicker;
            if (e.NewElement != null)
            {
                if (Control == null)
                {
                    var textField = CreateNativeControl();
                    textField.SetOnClickListener(CustomPickerListener.Instance);
                    textField.InputType = InputTypes.Null;
                    SetNativeControl(textField);
                }
            }`

I also update the code in repo.

**Comment by BalsamIbrahim** [comment]
yaa .. i will it but no any change on text button 
is still Done and Cancel but i need change text to arabic text

**Comment by sumeyyaarar** [comment]
Fixed the bug and commit changes to repo.

**Comment by BalsamIbrahim** [comment]
Thank you ..

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
