### ISSUE TITLE
Change Title Color

### ISSUE THREAD

**Issue by BalsamIbrahim** [sumeyyaarar/XamarinFormsCustomPicker#3]
i need change title color to black if picker disabled because title color not clear to users 
but i don't know why not change title color i using material xamarin forms.

![Screenshot_2019-11-19-12-04-36](https://user-images.githubusercontent.com/34779906/69145833-37490480-0ad7-11ea-9c70-360bc62c908b.png)

code: 
![Capture](https://user-images.githubusercontent.com/34779906/69145910-5ba4e100-0ad7-11ea-8c81-b787ce0b7539.PNG)

![Capture1](https://user-images.githubusercontent.com/34779906/69145918-5f386800-0ad7-11ea-8b84-d4449bb76b3e.PNG)

**Comment by sumeyyaarar** [comment]
Hello, you want to change the placeholder color of picker right?

**Comment by BalsamIbrahim** [comment]
Hello, yes .. can you help me .?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by sumeyyaarar** [comment]
Can you try this please:

`<renderers:CustomPicker TitleColor="Green" Title="Select an item" TextColor="DarkOrange" DoneButtonText="My Custom Done Text" CancelButtonText="My Custom Cancel Text" />`

**Comment by BalsamIbrahim** [comment]
If Status picker is enabled, you won't find a problem, but if you disable the picker, it won't work
[cid:image001.png@01D5A05E.ADA3A290]

[cid:image002.png@01D5A05E.C0B931B0]

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by sumeyyaarar** [comment]
`<renderers:CustomPicker TitleColor="Green" Title="Select an item" TextColor="DarkOrange" IsEnabled="False" DoneButtonText="My Other Custom Done Text" CancelButtonText="My Other Custom Cancel Text"/>`

It works like this for me?

**Comment by sumeyyaarar** [comment]
By the way if you want to change title color dynamically when change IsEnable property, I think you can use Converter for this.

**Comment by BalsamIbrahim** [comment]
Yaa .. but I use material
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/visual/material-visual
i think the problem because i use it
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by BalsamIbrahim** [comment]
I use your code but not solved is problem

[cid:image001.png@01D5A065.266BFCD0]

[cid:image002.png@01D5A065.3E160830]

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by sumeyyaarar** [comment]
Ok, I will try with the material visual and update you.

**Comment by BalsamIbrahim** [comment]
Ok .. thank you so much 😊

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by sumeyyaarar** [comment]
I tried with material too and it is still work for me. Here is how I do it. I added a gesture to change Title Color dynamically:

```
<StackLayout>
            <renderers:CustomPicker x:Name="picker" Visual="Material" Title="Select an item" 
                                TextColor="Orange"
                                TitleColor="Violet"  
                                DoneButtonText="My Custom Done Text"
                                 IsEnabled="False"
                                Focused="CustomPicker_Focused"
                                Unfocused="picker_Unfocused"
                                CancelButtonText="My Custom Cancel Text" />
            <StackLayout.GestureRecognizers>
                <TapGestureRecognizer Tapped="TapGestureRecognizer_Tapped"/>
            </StackLayout.GestureRecognizers>
        </StackLayout>
```

Code:

```
       private void CustomPicker_Focused(object sender, FocusEventArgs e)
        {
            picker.IsEnabled = true;
        }

        private void picker_Unfocused(object sender, FocusEventArgs e)
        {
            picker.IsEnabled = false;
            picker.TitleColor = Color.Violet;
        }

        private void TapGestureRecognizer_Tapped(object sender, EventArgs e)
        {
            picker.IsEnabled = true;
            picker.TitleColor = Color.Aquamarine;
        }
```
